name: 🚀 CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
      GCS_PROJECT_ID: ${{ secrets.GCS_PROJECT_ID }}
      GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
      GCS_KEYFILE: ./gcs-key.json

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🧪 Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: 📦 Install dependencies
      run: npm install

    - name: 🧪 Run tests
      run: npm test

    - name: 🐳 Build Docker image
      run: docker build -t secure-chat-app .

    # Optional: Push to Docker Hub
    - name: 🔐 Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 📤 Push image
      run: docker tag secure-chat-app your-dockerhub-username/secure-chat-app:latest &&
           docker push your-dockerhub-username/secure-chat-app:latest

    # Optional: Deploy to server (e.g. SSH, Render, etc.)
    # - name: 🚀 Deploy to server
    #   run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'docker pull ... && docker-compose up -d'